---
stages:
  - build
  - docker
  - acceptance

## Uncomment the following sections to enable docker, image building and
## acceptance

build:
  stage: build
  image: golang:alpine
  artifacts:
    paths:
      - bin/
  script:
    # - echo do something to build the binary or whatever
    - ls -la
    - go build -v -o bin/pooling cmd/main.go
    - cp .env.conf bin/.env.conf
    - ls -la bin/

build_image:
  stage: docker
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    # - echo As a helper here you have a sample of how to build and push a \
    # docker image to the provided gitlab registry.
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest

# Uncomment the acceptance step and do not remove or edit, this step is
# required for us to accept your submission!

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only: 
    - master
  dependencies: []
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address http://pooling:9091 acceptance
